const quotes = [
    'Nothing frees up the mind better than a good session of football with friends.',
    'Man knows so much, and controls so little.',
    "We don\'t write for others, we write for ourselves. Writing helps in forming ideas, which thinking alone can\'t do.",
    'Nothing in life is a waste of time, every experience teaches you something.',
    'Rebellion is almost as stupid as obedience. In either case you let yourself be defined by what they tell you to do.',
    "Everybody worries about what others think of them - the truth is, it doesn\'t really matter.",
    "Find a question that makes the world interesting. People who do great things look at the same world everyone else does, but notice some odd detail that\'s compellingly mysterious.",
    "There\'s no switch inside you that magically flips when you turn a certain age or graduate from some institution. You start being an adult when you decide to take responsibility for your life. You can do that at any age.",
    "Meditation is running your brain in debug mode until you realise you\'re just a subroutine in a larger program.",
    "Like rich food, idleness only seems desirable when you don\'t get enough of it. Humans were designed to work, just like they were designed to eat vitamins, minerals and fibers.",
    "People get so many ideas in the shower because that\'s a kind of meditation. Meditation leads to new ideas and thoughts.",
    'The reason some people can work on hard problems is that they have long uninterrupted periods of time. A couple interruptions can ruin an entire day.',
    'Achieving something significant requires staring failure in the eye every day for years.',
    "Don\'t stumble over something behind you.",
    'Merely measuring something has an uncanny tendency to improve it.',
    'Nothing ever goes right 100% of the time.',
    "Failing is fine, focus on recovery. There\'s no excuse for drowning.",
    "Don\'t be hapless and battered by life.",
    'Research is all about asking the right questions.',
    'Drawing is like meditating when you look at your surroundings while being aware.',
    'Stop doing fake work.',
    "If you\'re not feeling motivated to do some work, then you just don\'t want it bad enough.",
    'ADHD is like a superpower - it amplifies whatever you do exponentially. So wield it carefully.',
    "Don\'t ignore your dreams; don\'t work too much; say what you think; cultivate friendships; be happy.",
    'We win because we are determined and disciplined. Not because we are superior.',
    'We will fight it, because we are frightened if it.',
    'Something that feels like play to you might look like work to others.',
    'Escape competition through authenticity.',
    'Informal language is the athletic clothing of ideas.',
    'Being a developer is having shallow knowledge of a lot of things and deep knowledge of a few things.',
    "It doesn\'t matter what you like or don\'t like. What matters is what is and what isn\'t.",
    'You are the only one standing in your way.',
    'Try to seek as much detail in daily life as possible, to not get stuck in the existing ways of thinking.',
    'Always keep learning, whether at work or in relationships.',
    "Don\'t wrestle with the air.",
    "Every act of conscious learning requires the willingness to suffer an injury to one\'s self-esteem. That is why young children, before they are aware of their own self-importance, learn so easily; and why older persons, especially if vain or important, cannot learn at all.",
    "It\'s dark because you are trying too hard. Lightly child, lightly. Learn to do everything lightly. Yes, feel lightly even though you\'re feeling deeply."
];

export default quotes;
